# Streamlit secrets
# Copy this file to .streamlit/secrets.toml and fill in your values.
# Streamlit Cloud / Community Cloud: set these in the app settings UI instead.

# OpenAI
OPENAI_API_KEY = "sk-REPLACE_ME"

# Optional: default model for UI if you want to override picker default
# DEFAULT_MODEL = "gpt-5-nano"
